spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info

logging:
  level:
    com.example.demo: debug
#    org.redisson : trace

nft:
  name: scam

--- # 로컬 환경

spring:
  profiles: local
  redis:
    host: localhost
    port: 6379

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/study
      username: sa

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
--- # 배포 환경

spring:
  profiles: cloud
  redis:
    host: clustercfg.test-memorydb.sytn5f.memorydb.ap-northeast-2.amazonaws.com
    port: 6379