spring:
  profiles:
    active: cloud

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info

logging:
  level:
    com.example.demo: debug
    org.redisson : trace
    io.lettuce: trace

nft:
  name: scam

---

spring:
  profiles: local

  redis:
    host: localhost

---

spring:
  profiles: cloud
  redis:
    host: clustercfg.test-memorydb.sytn5f.memorydb.ap-northeast-2.amazonaws.com
    port: 6379
    timeout: 5000
