spring:
  profiles:
    active: local
    include: lettuce-client

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info

logging:
  level:
    com.example.demo: debug

nft:
  name: scam

---

spring:
  profiles: local

  redis:
    host: localhost

---

spring:
  profiles: cloud

  redis:
    host: test-cluster.sytn5f.ng.0001.apn2.cache.amazonaws.com
