spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info

logging:
  level:
    com.example.demo: debug
#    org.redisson : trace

nft:
  name: scam

---

spring:
  profiles: local
  redis:
    host: localhost
    port: 6379

---

spring:
  profiles: cloud
  redis:
    host: clustercfg.test-memorydb.sytn5f.memorydb.ap-northeast-2.amazonaws.com
    port: 6379