spring:
  profiles:
    active: cloud
    include: lettuce-client

management:
  endpoints:
    web:
      exposure:
        include: health, beans, info

logging:
  level:
    com.example.demo: debug

nft:
  name: scam

---

spring:
  profiles: local

  redis:
    host: localhost

---

spring:
  profiles: cloud

  redis:
    host: clustercfg.test-memorydb.sytn5f.memorydb.ap-northeast-2.amazonaws.com
