spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # 콘솔로 출력한다. (sysout)
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 로그로 출력한다.
#    org.hibernate.type: trace