spring:
  #datasource:
    #url: jdbc:h2:tcp://localhost/~/querydsl
    #username: sa
    #driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug